### ISSUE TITLE
Add support for plasma 6

### ISSUE THREAD

**Issue by hazel-bunny** [MartinF99/plasma-classic-wallpapers#1]
When these wallpapers are installed with cmake, they don't show up in the wallpaper kcm because they don't have metadata.json 

https://develop.kde.org/docs/plasma/widget/porting_kf6/

Please convert the metadata.desktop files to json. Thanks in advance

**Comment by MartinF99** [comment]
I just converted the json files with desktoptojson, can you check whether it works for you?

**Comment by MartinF99** [comment]
It seems to work on my end now, so marking this as fixed
